# Generated by Django 4.2.6 on 2023-10-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsspskov', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abouttext',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterField(
            model_name='newslist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
