# Generated by Django 4.2.6 on 2023-10-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsspskov', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(max_length=18),
        ),
    ]
